/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.kasirApp.swing;
import com.kasirApp.helper.ThemeColor;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Nasyikh Al-Qusyairy
 */
public class Card extends MyPanel {

    /**
     * Creates new form Card
     */
    public Card() {
        initComponents();
    }
    
    private boolean isDark;
    private String title;
    private String subtitle;
    private String body;
    
    public void setIsDark(boolean opt){
        isDark = opt;
        if (opt) {
            cardTitle.setForeground(Color.WHITE);
            cardSubtitle.setForeground(Color.WHITE);
            cardBody.setForeground(Color.WHITE);
        }else{
            cardTitle.setForeground(Color.BLACK);
            cardSubtitle.setForeground(ThemeColor.SECONDARY);
            cardBody.setForeground(Color.BLACK);
        }
    }
    
    public void setTitle(String str){
        title = str;
        cardTitle.setText(str);
    }
    public void setSubtitle(String str){
        subtitle = str;
        cardSubtitle.setText(str);
    }
    public void setBody(String str){
        body = str;
        cardBody.setText("<html><body><p align='justify'>"+str+"</p></body></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardTitle = new javax.swing.JLabel();
        cardSubtitle = new javax.swing.JLabel();
        cardBody = new javax.swing.JLabel();

        cardTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cardTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardTitle.setText("Card Title");

        cardSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cardSubtitle.setForeground(ThemeColor.SECONDARY);
        cardSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardSubtitle.setText("Subtitle text");

        cardBody.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cardBody.setText("<html><body><p align=\"justify\"> Lorem ipsum dolor sit amet commodo dis a ipsum hendrerit dapibus phasellus lacinia habitant ac urna donec aliquet sapien interdum vivamus tempus pede netus suscipit iaculis quis quam lectus dictum </p></body></html>");
        cardBody.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(cardSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardBody, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cardTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardSubtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardBody, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cardBody;
    private javax.swing.JLabel cardSubtitle;
    private javax.swing.JLabel cardTitle;
    // End of variables declaration//GEN-END:variables
}
