/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kasirApp.form;
import com.kasirApp.helper.FileExtension;
import com.kasirApp.helper.ThemeColor;
import com.kasirApp.model.TabelBarangModel;
import com.kasirApp.modelData.DataBarangModel;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.nio.file.Files;

/**
 *
 * @author Nasyikh Al-Qusyairy
 */
public class DataBarangForm extends javax.swing.JFrame {

    private TabelBarangModel model;
    private boolean Editing;
    private String kode = "";
    private String namaBarang = "";
    private String harga = "";
    private String deskripsi = "-";
    private String foto = getClass().getResource("/com/kasirApp/img/noimage.png").getPath().replace("\\", "\\\\").replace("%20", " ");
   
    public void setKode(String str){
        kode=str;
        inpKode.setText(str);
        setEditing(true);
        String[] data = DataBarangModel.getByKode(str);
        setNamaBarang(data[1]);
        setHarga(data[2]);
        setDeskripsi(data[3]);
        setFoto(data[4]);
    } 
    public void setNamaBarang(String str){
        namaBarang = str;
        inpNamaBarang.setText(str);
    }
    public void setHarga(String str){
        harga = str;
        inpHarga.setText(str);
    }
    public void setDeskripsi(String str){
        deskripsi = str;
        inpDeskripsi.setText(str);
    }
    public void setFoto(String filename){
        foto = filename.replace("\\", "\\\\").replace("%20", " ");
        ImageIcon icon = new ImageIcon(filename);
        Image image = icon.getImage().getScaledInstance(imgPreview.getWidth(), imgPreview.getHeight(), Image.SCALE_SMOOTH);
        imgPreview.setIcon(new ImageIcon(image));
    }
    public void setEditing(boolean bool){
        Editing = bool;
        inpKode.setEditable(!bool);
    }
    
     public void setKode(){
        kode = inpKode.getText().trim();
    } 
    public void setNamaBarang(){
        namaBarang = inpNamaBarang.getText().trim();
    }
    public void setHarga(){
        harga = inpHarga.getText().trim();
    }
    public void setDeskripsi(){
        deskripsi = inpDeskripsi.getText().trim();
    }
 
    /**
     * Creates new form NewJFrame
     */
    public DataBarangForm() {
        initComponents();
        setLocationRelativeTo(null);
        setEditing(false);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
    }
    
    public DataBarangForm(TabelBarangModel model) {
        this.model = model;
        initComponents();
        setLocationRelativeTo(null);
        setEditing(false);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
    }
    
    public DataBarangForm(TabelBarangModel model,String kode) {
        this.model = model;
        initComponents();
        setLocationRelativeTo(null);
        setKode(kode);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        primaryButton2 = new com.kasirApp.swing.button.PrimaryButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inpKode = new com.kasirApp.swing.MyTextField();
        jLabel2 = new javax.swing.JLabel();
        inpNamaBarang = new com.kasirApp.swing.MyTextField();
        jLabel3 = new javax.swing.JLabel();
        inpHarga = new com.kasirApp.swing.MyTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inpDeskripsi = new javax.swing.JTextArea();
        btnSimpan = new com.kasirApp.swing.button.PrimaryButton();
        btnUpload = new com.kasirApp.swing.button.PrimaryButton();
        imgPreview = new javax.swing.JLabel();

        primaryButton2.setText("primaryButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Barang");
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);

        jPanel1.setBackground(ThemeColor.LIGHT);
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setText("Kode");

        inpKode.setEditable(false);
        inpKode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inpKodeKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("Nama Barang");

        inpNamaBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inpNamaBarangKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setText("Harga");

        inpHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inpHargaKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setText("Deskripsi");

        inpDeskripsi.setColumns(20);
        inpDeskripsi.setLineWrap(true);
        inpDeskripsi.setRows(5);
        inpDeskripsi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inpDeskripsiKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(inpDeskripsi);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUpload.setText("Upload Foto");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        imgPreview.setBackground(ThemeColor.SECONDARY);
        imgPreview.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/com/kasirApp/img/noimage.png")).getImage().getScaledInstance(182, 182, Image.SCALE_SMOOTH)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(0, 219, Short.MAX_VALUE))
                            .addComponent(inpKode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inpNamaBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inpHarga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgPreview, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imgPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String[] dataset = {kode,namaBarang,harga,deskripsi,foto};
        int res = 0;
        if (!Editing) {
            res = DataBarangModel.insert(dataset);
        }else{
            res = DataBarangModel.update(dataset);
        }
        if (res==1) {
            model.setDataVector(DataBarangModel.get(), DataBarangModel.TABLE_HEADER);
            setVisible(false);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void inpKodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inpKodeKeyReleased
        setKode();
    }//GEN-LAST:event_inpKodeKeyReleased

    private void inpNamaBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inpNamaBarangKeyReleased
        setNamaBarang();
    }//GEN-LAST:event_inpNamaBarangKeyReleased

    private void inpHargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inpHargaKeyReleased
        inpHarga.setText(inpHarga.getText().replaceAll("[^0-9]", ""));
        setHarga();
    }//GEN-LAST:event_inpHargaKeyReleased

    private void inpDeskripsiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inpDeskripsiKeyReleased
        setDeskripsi();
    }//GEN-LAST:event_inpDeskripsiKeyReleased

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        try {
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        if (file!=null) {
            String ext = FileExtension.get(file);
            if (!ext.toLowerCase().equals(".png")&&!ext.toLowerCase().equals(".jpg")&&!ext.toLowerCase().equals(".jpeg")) {
                throw new Exception("Jenis file tidak didukung!");
            }
            String filename = file.getAbsolutePath();
            foto = filename;
            ImageIcon icon = new ImageIcon(filename);
            Image image = icon.getImage().getScaledInstance(imgPreview.getWidth(), imgPreview.getHeight(), Image.SCALE_SMOOTH);
            imgPreview.setIcon(new ImageIcon(image));
        }
        } catch (Exception err) {
            String msg = err.getMessage()==null?"Terjadi kesalahan!":err.getMessage();
            JOptionPane.showMessageDialog(null, msg, "Error", 0);
        }
    }//GEN-LAST:event_btnUploadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataBarangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataBarangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataBarangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataBarangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataBarangForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.kasirApp.swing.button.PrimaryButton btnSimpan;
    private com.kasirApp.swing.button.PrimaryButton btnUpload;
    private javax.swing.JLabel imgPreview;
    private javax.swing.JTextArea inpDeskripsi;
    private com.kasirApp.swing.MyTextField inpHarga;
    private com.kasirApp.swing.MyTextField inpKode;
    private com.kasirApp.swing.MyTextField inpNamaBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.kasirApp.swing.button.PrimaryButton primaryButton2;
    // End of variables declaration//GEN-END:variables
}
