/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.kasirApp.panel;
import com.kasirApp.form.DataBarangForm;
import com.kasirApp.helper.ThemeColor;
import com.kasirApp.model.TabelBarangModel;
import com.kasirApp.modelData.DataBarangModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Nasyikh Al-Qusyairy
 */
public class DataBarang extends javax.swing.JPanel {

    private TabelBarangModel model;
    private String kode="";
    /**
     * Creates new form DataBarang
     */
    public DataBarang() {
        initComponents();
        model = new TabelBarangModel();
        tblBarang.setModel(model);
    }
    
    public void refresh(){
        model.setDataVector(DataBarangModel.get(), DataBarangModel.TABLE_HEADER);
        kode="";
        detail.setTitle("Nama Barang");
        detail.setSubtitle("Rp. 0");
        detail.setBody("Deskripsi (Pilih item untuk menampilkan)");
        detail.setImageURL(getClass().getResource("/com/kasirApp/img/noimage.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnTambah = new com.kasirApp.swing.button.PrimaryButton();
        btnHapus = new com.kasirApp.swing.button.DangerButton();
        btnEdit = new com.kasirApp.swing.button.WarningButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarang = new com.kasirApp.swing.myTable();
        inpCari = new com.kasirApp.swing.MyTextField();
        btnRefresh = new com.kasirApp.swing.button.SecondaryButton();
        btnKosongkan = new com.kasirApp.swing.button.SecondaryButton();
        detail = new com.kasirApp.swing.ImageCard();

        setBackground(ThemeColor.LIGHT);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Data Barang");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Detail");

        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kasirApp/icon/Plus.png"))); // NOI18N
        btnTambah.setText("Tambah Data");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kasirApp/icon/Hapus.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kasirApp/icon/Edit.png"))); // NOI18N
        btnEdit.setText("Ubah");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Kode", "Nama Barang", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBarang.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBarang);

        inpCari.setText("Cari di sini...");
        inpCari.setToolTipText("");
        inpCari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inpCariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inpCariFocusLost(evt);
            }
        });
        inpCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inpCariKeyReleased(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kasirApp/icon/Refresh.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnKosongkan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kasirApp/icon/Kosongkan.png"))); // NOI18N
        btnKosongkan.setText("Kosongkan");
        btnKosongkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKosongkanActionPerformed(evt);
            }
        });

        detail.setBody("Daskripsi (Pilih item untuk menampilkan)");
        detail.setBorderColor(ThemeColor.SECONDARY400);
        detail.setSubtitle("Rp. 0");
        detail.setTitle("Nama Barang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpCari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKosongkan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inpCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKosongkan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        new DataBarangForm(model).setVisible(true);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        kode = tblBarang.getModel().getValueAt(tblBarang.getSelectedRow(), 1).toString();
        String[] data = DataBarangModel.getByKode(kode);
        detail.setTitle(data[1]);
        detail.setSubtitle("Rp. "+data[2]);
        detail.setBody(data[3]);
        detail.setImage(data[4]);
    }//GEN-LAST:event_tblBarangMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (!kode.equals("")) {
            new DataBarangForm(model,kode).setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Pilih item terlebih dahulu!", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        if (!kode.equals("")) {
            int confirm = JOptionPane.showConfirmDialog(null, "Data akan hilang untuk selamanya. Anda yakin?", "Hapus data : "+kode, 0);
            if (confirm==JOptionPane.OK_OPTION) {
                DataBarangModel.delete(kode);
                refresh();   
            }
        }else{
            JOptionPane.showMessageDialog(null, "Pilih item terlebih dahulu!", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKosongkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKosongkanActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Seluruh data akan hilang untuk selamanya. Anda yakin?", "Kosongkan data", 0);
        if (confirm==JOptionPane.OK_OPTION) {
            DataBarangModel.empty();
            refresh();   
        }
    }//GEN-LAST:event_btnKosongkanActionPerformed

    private void inpCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inpCariKeyReleased
        model.setDataVector(DataBarangModel.search(inpCari.getText().trim()), DataBarangModel.TABLE_HEADER);
    }//GEN-LAST:event_inpCariKeyReleased

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        refresh();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void inpCariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpCariFocusGained
       if (inpCari.getText().equals("Cari di sini...")) {
            inpCari.setText("");
        }
    }//GEN-LAST:event_inpCariFocusGained

    private void inpCariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpCariFocusLost
        if (inpCari.getText().equals("")) {
            inpCari.setText("Cari di sini...");
        }
    }//GEN-LAST:event_inpCariFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.kasirApp.swing.button.WarningButton btnEdit;
    private com.kasirApp.swing.button.DangerButton btnHapus;
    private com.kasirApp.swing.button.SecondaryButton btnKosongkan;
    private com.kasirApp.swing.button.SecondaryButton btnRefresh;
    private com.kasirApp.swing.button.PrimaryButton btnTambah;
    private com.kasirApp.swing.ImageCard detail;
    private com.kasirApp.swing.MyTextField inpCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.kasirApp.swing.myTable tblBarang;
    // End of variables declaration//GEN-END:variables
}
