/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.kasirApp.panel;
import com.kasirApp.helper.ThemeColor;
import com.kasirApp.model.TabelTransaksiBaruModel;
import com.kasirApp.modelData.DataTransaksiBaruModel;
import com.kasirApp.modelData.DataTransaksiModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.text.DateFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author Nasyikh Al-Qusyairy
 */
public class TransaksiBaru extends javax.swing.JPanel {

    private String idTransaksi;
    private String total="0";
    private String waktu;
    private String kode="";
    private DataTransaksiBaruModel model = new DataTransaksiBaruModel();
    private TabelTransaksiBaruModel modelTable = new TabelTransaksiBaruModel(model.get(), model.header);
    
    public void refresh(){
        setIdTransaksi(Integer.toString(((int) Math.floor(Math.random() * Math.pow(10, 7)))));
        setTotal("0");
        resetWaktu();
        resetModel();
        inpJumlah.setText("");
        inpKode.setText("");
    }
    
    public void resetWaktu(){
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyy | HH:mm");
	Date date = new Date();
        waktu = dateFormat.format(date);
    }
    
    public void setTotal(String n ){
        total=n;
        lblTotal.setText(n);
    }
    
    public void setIdTransaksi(String str){
        idTransaksi=str;
        lblIdTransaksi.setText(str);
    }
    
    public void resetModel(){
        model = new DataTransaksiBaruModel();
        modelTable.setDataVector(model.get(), model.header);
    }
    
    /**
     * Creates new form DataBarang
     */
    public TransaksiBaru() {
        initComponents();
        setIdTransaksi(Integer.toString(((int) Math.floor(Math.random() * Math.pow(10, 7)))));
        resetWaktu();
        tblTransaksiBaru.setModel(modelTable);
    }
    
    public boolean bayar(){
        String uang = JOptionPane.showInputDialog(null,"Masukkan uang pembayaran","Pembayaran",JOptionPane.QUESTION_MESSAGE);
        boolean status = false;
        try {
            int kembalian = Integer.parseInt(uang)-Integer.parseInt(total);
            if (kembalian<0) {
               JOptionPane.showMessageDialog(null, "Uang pembayaran tidak cukup", "Peringatan", JOptionPane.WARNING_MESSAGE);
               bayar();
            }else{
                JOptionPane.showMessageDialog(null, "Kembalian : "+Integer.toString(kembalian),"Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                status = true;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Pembayaran dibatalkan", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
        return status;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableDark1 = new com.kasirApp.swing.myTable();
        jLabel3 = new javax.swing.JLabel();
        inpKode = new com.kasirApp.swing.MyTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inpJumlah = new com.kasirApp.swing.MyTextField();
        jLabel1 = new javax.swing.JLabel();
        lblIdTransaksi = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnBayar = new com.kasirApp.swing.button.SuccessButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTransaksiBaru = new com.kasirApp.swing.myTable();
        btnHapus = new com.kasirApp.swing.button.DangerButton();
        btnRefresh = new com.kasirApp.swing.button.SecondaryButton();
        btnTambah = new com.kasirApp.swing.button.PrimaryButton();

        tableDark1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableDark1);

        setBackground(ThemeColor.LIGHT);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Transaksi Baru");

        inpKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpKodeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("Kode");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("Jumlah");

        inpJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpJumlahActionPerformed(evt);
            }
        });
        inpJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inpJumlahKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Id Transaksi : ");

        lblIdTransaksi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblIdTransaksi.setText("##########");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTotal.setForeground(ThemeColor.PRIMARY);
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("0");

        btnBayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kasirApp/icon/Bayar.png"))); // NOI18N
        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        tblTransaksiBaru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode", "Nama", "Harga Satuan", "Jumlah", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTransaksiBaru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransaksiBaruMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTransaksiBaru);

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kasirApp/icon/Hapus.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kasirApp/icon/Refresh.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kasirApp/icon/Plus.png"))); // NOI18N
        btnTambah.setText("Tambahkan");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(inpKode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inpJumlah, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 382, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIdTransaksi))
                            .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inpJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdTransaksi)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        refresh();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String kode = inpKode.getText()==null?"":inpKode.getText();
        if (!kode.equals("")) {
            String jumlah = inpJumlah.getText()==null||inpJumlah.getText().equals("")||inpJumlah.getText().equals("0")?"1":inpJumlah.getText();
            String[] dataset = {idTransaksi,kode,jumlah};
            setTotal(model.add(dataset));
            modelTable.setDataVector(model.get(), model.header);
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        if (!kode.equals("")) {
            setTotal(model.delete(kode));
            modelTable.setDataVector(model.get(), model.header);
            kode="";
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tblTransaksiBaruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransaksiBaruMouseClicked
        kode = tblTransaksiBaru.getModel().getValueAt(tblTransaksiBaru.getSelectedRow(), 1).toString();
    }//GEN-LAST:event_tblTransaksiBaruMouseClicked

    private void inpJumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inpJumlahKeyReleased
        inpJumlah.setText(inpJumlah.getText().replaceAll("[^0-9]", ""));
    }//GEN-LAST:event_inpJumlahKeyReleased

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        if (!total.equals("0")) {
            if (bayar()) {
                model.insert();
                String[] dataset = {idTransaksi,waktu,total};
                DataTransaksiModel.insert(dataset);
                refresh();
            }
        }
    }//GEN-LAST:event_btnBayarActionPerformed

    private void inpKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpKodeActionPerformed
        btnTambahActionPerformed(evt);
    }//GEN-LAST:event_inpKodeActionPerformed

    private void inpJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpJumlahActionPerformed
        btnTambahActionPerformed(evt);
    }//GEN-LAST:event_inpJumlahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.kasirApp.swing.button.SuccessButton btnBayar;
    private com.kasirApp.swing.button.DangerButton btnHapus;
    private com.kasirApp.swing.button.SecondaryButton btnRefresh;
    private com.kasirApp.swing.button.PrimaryButton btnTambah;
    private com.kasirApp.swing.MyTextField inpJumlah;
    private com.kasirApp.swing.MyTextField inpKode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblIdTransaksi;
    private javax.swing.JLabel lblTotal;
    private com.kasirApp.swing.myTable tableDark1;
    private com.kasirApp.swing.myTable tblTransaksiBaru;
    // End of variables declaration//GEN-END:variables
}
