/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kasirApp.main;
import com.kasirApp.form.LoginForm;
import com.kasirApp.helper.ThemeColor;
import javax.swing.JOptionPane;
/**
 *
 * @author Nasyikh Al-Qusyairy
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Main() {
        initComponents();
        LoginForm.showloginDialog(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        darkButton1 = new com.kasirApp.swing.button.DarkButton();
        darkButton2 = new com.kasirApp.swing.button.DarkButton();
        darkButton3 = new com.kasirApp.swing.button.DarkButton();
        darkButton4 = new com.kasirApp.swing.button.DarkButton();
        darkButton5 = new com.kasirApp.swing.button.DarkButton();
        tabbedPane = new com.kasirApp.swing.MaterialTabbed();
        dashboard2 = new com.kasirApp.panel.Dashboard();
        dataTransaksi2 = new com.kasirApp.panel.TransaksiBaru();
        dataBarang2 = new com.kasirApp.panel.DataBarang();
        ubahKataSandi1 = new com.kasirApp.panel.UbahKataSandi();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Kasir");

        jPanel1.setBackground(ThemeColor.LIGHT);

        jPanel2.setBackground(new java.awt.Color(33, 37, 41));

        jPanel3.setBackground(ThemeColor.PRIMARY);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Aplikasi Kasir");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(78, 78, 78))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        darkButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kasirApp/icon/Dashboard.png"))); // NOI18N
        darkButton1.setText("Dashboard");
        darkButton1.setColorOver(ThemeColor.GRAY800);
        darkButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        darkButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        darkButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDashboard(evt);
            }
        });

        darkButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kasirApp/icon/Keluar.png"))); // NOI18N
        darkButton2.setText("Keluar");
        darkButton2.setColorOver(ThemeColor.GRAY800);
        darkButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        darkButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        darkButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkButton2ActionPerformed(evt);
            }
        });

        darkButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kasirApp/icon/Transaksi.png"))); // NOI18N
        darkButton3.setText("Transaksi");
        darkButton3.setColorOver(ThemeColor.GRAY800);
        darkButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        darkButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        darkButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openTransaksi(evt);
            }
        });

        darkButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kasirApp/icon/Barang.png"))); // NOI18N
        darkButton4.setText("Data Barang");
        darkButton4.setColorOver(ThemeColor.GRAY800);
        darkButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        darkButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        darkButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDataBarang(evt);
            }
        });

        darkButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kasirApp/icon/Password.png"))); // NOI18N
        darkButton5.setText("Ubah Kata Sandi");
        darkButton5.setColorOver(ThemeColor.GRAY800);
        darkButton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        darkButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        darkButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(darkButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(darkButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(darkButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(darkButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(darkButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(darkButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(darkButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(darkButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(darkButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(darkButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 402, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Dashboard", dashboard2);
        tabbedPane.addTab("Transaksi", dataTransaksi2);
        tabbedPane.addTab("Barang", dataBarang2);
        tabbedPane.addTab("Sandi", ubahKataSandi1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openDashboard(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openDashboard
        tabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_openDashboard

    private void openTransaksi(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openTransaksi
        tabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_openTransaksi

    private void openDataBarang(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openDataBarang
        tabbedPane.setSelectedIndex(2);
    }//GEN-LAST:event_openDataBarang

    private void darkButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkButton2ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Anda yakin ingin keluar?", "Keluar", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirm == JOptionPane.OK_OPTION) {
            System.exit(0);
        }
        
    }//GEN-LAST:event_darkButton2ActionPerformed

    private void darkButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkButton5ActionPerformed
        tabbedPane.setSelectedIndex(3);
    }//GEN-LAST:event_darkButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.kasirApp.swing.button.DarkButton darkButton1;
    private com.kasirApp.swing.button.DarkButton darkButton2;
    private com.kasirApp.swing.button.DarkButton darkButton3;
    private com.kasirApp.swing.button.DarkButton darkButton4;
    private com.kasirApp.swing.button.DarkButton darkButton5;
    private com.kasirApp.panel.Dashboard dashboard2;
    private com.kasirApp.panel.DataBarang dataBarang2;
    private com.kasirApp.panel.TransaksiBaru dataTransaksi2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private com.kasirApp.swing.MaterialTabbed tabbedPane;
    private com.kasirApp.panel.UbahKataSandi ubahKataSandi1;
    // End of variables declaration//GEN-END:variables
}
